import pic1 from './products/dress-one.avif';
import pic2 from './products/dress-two.jpg';
import pic3 from './products/dress-three.jpg';


interface product{
    id:string|number,
    link:string
    name:string,
    price:string|number,
    stock:string|number,
    category:string,
    shortDescription:string,
    longDescription:string,
    picture1:string,
    picture2:string,
    picture3:string,
}

const Products: product[] = [
    {
        id:1,
        link:'',
        name:'shirt',
        price:'20000',
        stock:'6',
        category:'Men Fashion',
        shortDescription:'',
        longDescription:'',
        picture1:pic1,
        picture2:'',
        picture3:'',
    },
    {
        id:2,
        link:'',
        name:'shirt',
        price:'20000',
        stock:'6',
        category:'Men Fashion',
        shortDescription:'',
        longDescription:'',
        picture1:pic2,
        picture2:'',
        picture3:'',
    },
    {
        id:3,
        link:'',
        name:'shirt',
        price:'20000',
        stock:'6',
        category:'Men Fashion',
        shortDescription:'',
        longDescription:'',
        picture1:pic3,
        picture2:'',
        picture3:'',
    },
    {
        id:4,
        link:'',
        name:'shirt',
        price:'20000',
        stock:'6',
        category:'Men Fashion',
        shortDescription:'',
        longDescription:'',
        picture1:pic1,
        picture2:'',
        picture3:'',
    },
    {
        id:5,
        link:'',
        name:'shirt',
        price:'20000',
        stock:'6',
        category:'Men Fashion',
        shortDescription:'',
        longDescription:'',
        picture1:pic2,
        picture2:'',
        picture3:'',
    },
    {
        id:6,
        link:'',
        name:'shirt',
        price:'20000',
        stock:'6',
        category:'Men Fashion',
        shortDescription:'',
        longDescription:'',
        picture1:pic3,
        picture2:'',
        picture3:'',
    },
    {
        id:7,
        link:'',
        name:'shirt',
        price:'20000',
        stock:'6',
        category:'Men Fashion',
        shortDescription:'',
        longDescription:'',
        picture1:pic1,
        picture2:'',
        picture3:'',
    },
    {
        id:8,
        link:'',
        name:'shirt',
        price:'20000',
        stock:'6',
        category:'Men Fashion',
        shortDescription:'',
        longDescription:'',
        picture1:pic2,
        picture2:'',
        picture3:'',
    },
    {
        id:9,
        link:'',
        name:'shirt',
        price:'20000',
        stock:'6',
        category:'Men Fashion',
        shortDescription:'',
        longDescription:'',
        picture1:pic3,
        picture2:'',
        picture3:'',
    },
]

export default Products